/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View } from 'react-native';
import CupertinoProgress from 'react-native-cupertino-progress';

export default class App extends Component {
  
  render() {
    return (
      <View style={styles.container}>
        <View style={{ width: 100, height: 200, backgroundColor: 'blue', alignItems: 'center' }} >
          <CupertinoProgress onSlidingComplete={this._onSlidingComplete} onValueChange={this._onValueChange} progress={60} size={40} magnification={45} color='red' style={{ borderRadius: 20, backgroundColor: 'pink' }} />
        </View>
        <View style={{ width: 200, height: 100, backgroundColor: 'blue', marginTop: 20 }} >
          <CupertinoProgress onSlidingComplete={this._onSlidingComplete} onValueChange={this._onValueChange} horizontal={true} progress={60} size={40} magnification={45} color='red' style={{ borderRadius: 20, backgroundColor: 'pink' }} />
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  }
});
